name: Testing Action

on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Testing action docker hub
        uses: ./
        with:
          image_name: sbaerlocher/test
          image_tag: do_not_use
          dockerfile: tests/.
          build_args: ANSIBLE_VERSION=2.9.0
          registry: registry.hub.docker.com
          registry_username: sbaerlocher
          registry_password: ${{ secrets.DOCKER_TOKEN }}

      - name: Testing action github pkg
        uses: ./
        with:
          image_name: test
          image_tag: do_not_use
          dockerfile: tests/.
          registry: docker.pkg.github.com/tinact/docker.image
          registry_username: sbaerlocher
          registry_password: ${{ secrets.GITHUB_TOKEN }}
